qiniu:
  ACCESS_KEY:  # 公钥
  SECRET_KEY:  # 私钥
  bucketname: ossmy  #存储空间名称
  path: http://oss.icodeme.cn/ #域名
  dir: img/ #指定文件夹

spring:
  servlet:
    multipart:
      enabled: true #是否启用http上传处理
      max-request-size: 100MB #最大请求文件的大小
      max-file-size: 50MB #设置单个文件最大长度




